/*
 * generated by Xtext 2.12.0
 */
package mdd.uni.petrinet.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import petrinet_xtext.ui.internal.Petrinet_xtextActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class PetrinetExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Petrinet_xtextActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return Petrinet_xtextActivator.getInstance().getInjector(Petrinet_xtextActivator.MDD_UNI_PETRINET_PETRINET);
	}
	
}
