/**
 * generated by Xtext 2.12.0
 */
package org.xtext.example.mydsl.petriNetz.impl;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.example.mydsl.petriNetz.PetriNetzPackage;
import org.xtext.example.mydsl.petriNetz.Token;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Token</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class TokenImpl extends MinimalEObjectImpl.Container implements Token
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected TokenImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return PetriNetzPackage.Literals.TOKEN;
  }

} //TokenImpl
