/**
 * generated by Xtext 2.12.0
 */
package org.xtext.example.mydsl.petriNetz.impl;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.xtext.example.mydsl.petriNetz.PetriNetzPackage;
import org.xtext.example.mydsl.petriNetz.Place;
import org.xtext.example.mydsl.petriNetz.TPArc;
import org.xtext.example.mydsl.petriNetz.Transition;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>TP Arc</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.petriNetz.impl.TPArcImpl#getTrg <em>Trg</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.petriNetz.impl.TPArcImpl#getSrc <em>Src</em>}</li>
 * </ul>
 *
 * @generated
 */
public class TPArcImpl extends ArcImpl implements TPArc
{
  /**
   * The cached value of the '{@link #getTrg() <em>Trg</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTrg()
   * @generated
   * @ordered
   */
  protected Place trg;

  /**
   * The cached value of the '{@link #getSrc() <em>Src</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSrc()
   * @generated
   * @ordered
   */
  protected Transition src;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected TPArcImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return PetriNetzPackage.Literals.TP_ARC;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Place getTrg()
  {
    if (trg != null && trg.eIsProxy())
    {
      InternalEObject oldTrg = (InternalEObject)trg;
      trg = (Place)eResolveProxy(oldTrg);
      if (trg != oldTrg)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, PetriNetzPackage.TP_ARC__TRG, oldTrg, trg));
      }
    }
    return trg;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Place basicGetTrg()
  {
    return trg;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setTrg(Place newTrg)
  {
    Place oldTrg = trg;
    trg = newTrg;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, PetriNetzPackage.TP_ARC__TRG, oldTrg, trg));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Transition getSrc()
  {
    if (src != null && src.eIsProxy())
    {
      InternalEObject oldSrc = (InternalEObject)src;
      src = (Transition)eResolveProxy(oldSrc);
      if (src != oldSrc)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, PetriNetzPackage.TP_ARC__SRC, oldSrc, src));
      }
    }
    return src;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Transition basicGetSrc()
  {
    return src;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setSrc(Transition newSrc)
  {
    Transition oldSrc = src;
    src = newSrc;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, PetriNetzPackage.TP_ARC__SRC, oldSrc, src));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case PetriNetzPackage.TP_ARC__TRG:
        if (resolve) return getTrg();
        return basicGetTrg();
      case PetriNetzPackage.TP_ARC__SRC:
        if (resolve) return getSrc();
        return basicGetSrc();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case PetriNetzPackage.TP_ARC__TRG:
        setTrg((Place)newValue);
        return;
      case PetriNetzPackage.TP_ARC__SRC:
        setSrc((Transition)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case PetriNetzPackage.TP_ARC__TRG:
        setTrg((Place)null);
        return;
      case PetriNetzPackage.TP_ARC__SRC:
        setSrc((Transition)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case PetriNetzPackage.TP_ARC__TRG:
        return trg != null;
      case PetriNetzPackage.TP_ARC__SRC:
        return src != null;
    }
    return super.eIsSet(featureID);
  }

} //TPArcImpl
