/*
 * generated by Xtext 2.12.0
 */
package org.xtext.example.mydsl.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.example.mydsl.parser.antlr.internal.InternalPetriNetzParser;
import org.xtext.example.mydsl.services.PetriNetzGrammarAccess;

public class PetriNetzParser extends AbstractAntlrParser {

	@Inject
	private PetriNetzGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalPetriNetzParser createParser(XtextTokenStream stream) {
		return new InternalPetriNetzParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Petrinet";
	}

	public PetriNetzGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(PetriNetzGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
