/**
 * generated by Xtext 2.12.0
 */
package mdd.uni.petrinet.ide;

import mdd.uni.petrinet.ide.AbstractPetrinetIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class PetrinetIdeModule extends AbstractPetrinetIdeModule {
}
