/**
 * generated by Xtext 2.12.0
 */
package mdd.uni.petrinet.petrinet.impl;

import mdd.uni.petrinet.petrinet.PetrinetPackage;
import mdd.uni.petrinet.petrinet.Token;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Token</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class TokenImpl extends MinimalEObjectImpl.Container implements Token
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected TokenImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return PetrinetPackage.Literals.TOKEN;
  }

} //TokenImpl
