/**
 * generated by Xtext 2.12.0
 */
package mdd.uni.petrinet.petrinet;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Place</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link mdd.uni.petrinet.petrinet.Place#getName <em>Name</em>}</li>
 *   <li>{@link mdd.uni.petrinet.petrinet.Place#getTokens <em>Tokens</em>}</li>
 *   <li>{@link mdd.uni.petrinet.petrinet.Place#getOut <em>Out</em>}</li>
 *   <li>{@link mdd.uni.petrinet.petrinet.Place#getIn <em>In</em>}</li>
 * </ul>
 *
 * @see mdd.uni.petrinet.petrinet.PetrinetPackage#getPlace()
 * @model
 * @generated
 */
public interface Place extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see mdd.uni.petrinet.petrinet.PetrinetPackage#getPlace_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link mdd.uni.petrinet.petrinet.Place#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Tokens</b></em>' containment reference list.
   * The list contents are of type {@link mdd.uni.petrinet.petrinet.Token}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Tokens</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Tokens</em>' containment reference list.
   * @see mdd.uni.petrinet.petrinet.PetrinetPackage#getPlace_Tokens()
   * @model containment="true"
   * @generated
   */
  EList<Token> getTokens();

  /**
   * Returns the value of the '<em><b>Out</b></em>' reference list.
   * The list contents are of type {@link mdd.uni.petrinet.petrinet.PTArc}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Out</em>' reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Out</em>' reference list.
   * @see mdd.uni.petrinet.petrinet.PetrinetPackage#getPlace_Out()
   * @model
   * @generated
   */
  EList<PTArc> getOut();

  /**
   * Returns the value of the '<em><b>In</b></em>' reference list.
   * The list contents are of type {@link mdd.uni.petrinet.petrinet.TPArc}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>In</em>' reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>In</em>' reference list.
   * @see mdd.uni.petrinet.petrinet.PetrinetPackage#getPlace_In()
   * @model
   * @generated
   */
  EList<TPArc> getIn();

} // Place
