/**
 * generated by Xtext 2.12.0
 */
package mdd.uni.petrinet.petrinet;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>PT Arc</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link mdd.uni.petrinet.petrinet.PTArc#getSource <em>Source</em>}</li>
 *   <li>{@link mdd.uni.petrinet.petrinet.PTArc#getTarget <em>Target</em>}</li>
 * </ul>
 *
 * @see mdd.uni.petrinet.petrinet.PetrinetPackage#getPTArc()
 * @model
 * @generated
 */
public interface PTArc extends Arc
{
  /**
   * Returns the value of the '<em><b>Source</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Source</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Source</em>' reference.
   * @see #setSource(Place)
   * @see mdd.uni.petrinet.petrinet.PetrinetPackage#getPTArc_Source()
   * @model
   * @generated
   */
  Place getSource();

  /**
   * Sets the value of the '{@link mdd.uni.petrinet.petrinet.PTArc#getSource <em>Source</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Source</em>' reference.
   * @see #getSource()
   * @generated
   */
  void setSource(Place value);

  /**
   * Returns the value of the '<em><b>Target</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Target</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Target</em>' reference.
   * @see #setTarget(Transition)
   * @see mdd.uni.petrinet.petrinet.PetrinetPackage#getPTArc_Target()
   * @model
   * @generated
   */
  Transition getTarget();

  /**
   * Sets the value of the '{@link mdd.uni.petrinet.petrinet.PTArc#getTarget <em>Target</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Target</em>' reference.
   * @see #getTarget()
   * @generated
   */
  void setTarget(Transition value);

} // PTArc
