/*
 * generated by Xtext 2.12.0
 */
package mdd.uni.petrinet.ide.contentassist.antlr;

import com.google.inject.Inject;
import java.util.HashMap;
import java.util.Map;
import mdd.uni.petrinet.ide.contentassist.antlr.internal.InternalPetrinetParser;
import mdd.uni.petrinet.services.PetrinetGrammarAccess;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;

public class PetrinetParser extends AbstractContentAssistParser {

	@Inject
	private PetrinetGrammarAccess grammarAccess;

	private Map<AbstractElement, String> nameMappings;

	@Override
	protected InternalPetrinetParser createParser() {
		InternalPetrinetParser result = new InternalPetrinetParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getArcAccess().getAlternatives(), "rule__Arc__Alternatives");
					put(grammarAccess.getPetrinetAccess().getGroup(), "rule__Petrinet__Group__0");
					put(grammarAccess.getPetrinetAccess().getGroup_3(), "rule__Petrinet__Group_3__0");
					put(grammarAccess.getPetrinetAccess().getGroup_3_0(), "rule__Petrinet__Group_3_0__0");
					put(grammarAccess.getPetrinetAccess().getGroup_3_1(), "rule__Petrinet__Group_3_1__0");
					put(grammarAccess.getPetrinetAccess().getGroup_3_2(), "rule__Petrinet__Group_3_2__0");
					put(grammarAccess.getPlaceAccess().getGroup(), "rule__Place__Group__0");
					put(grammarAccess.getPlaceAccess().getGroup_3(), "rule__Place__Group_3__0");
					put(grammarAccess.getPlaceAccess().getGroup_3_0(), "rule__Place__Group_3_0__0");
					put(grammarAccess.getPlaceAccess().getGroup_3_1(), "rule__Place__Group_3_1__0");
					put(grammarAccess.getPlaceAccess().getGroup_3_2(), "rule__Place__Group_3_2__0");
					put(grammarAccess.getTokenAccess().getGroup(), "rule__Token__Group__0");
					put(grammarAccess.getTransitionAccess().getGroup(), "rule__Transition__Group__0");
					put(grammarAccess.getTransitionAccess().getGroup_3(), "rule__Transition__Group_3__0");
					put(grammarAccess.getTransitionAccess().getGroup_3_0(), "rule__Transition__Group_3_0__0");
					put(grammarAccess.getTransitionAccess().getGroup_3_1(), "rule__Transition__Group_3_1__0");
					put(grammarAccess.getPTArcAccess().getGroup(), "rule__PTArc__Group__0");
					put(grammarAccess.getTPArcAccess().getGroup(), "rule__TPArc__Group__0");
					put(grammarAccess.getPetrinetAccess().getNameAssignment_1(), "rule__Petrinet__NameAssignment_1");
					put(grammarAccess.getPetrinetAccess().getPlacesAssignment_3_0_2(), "rule__Petrinet__PlacesAssignment_3_0_2");
					put(grammarAccess.getPetrinetAccess().getTransitionsAssignment_3_1_2(), "rule__Petrinet__TransitionsAssignment_3_1_2");
					put(grammarAccess.getPetrinetAccess().getArcsAssignment_3_2_2(), "rule__Petrinet__ArcsAssignment_3_2_2");
					put(grammarAccess.getPlaceAccess().getNameAssignment_1(), "rule__Place__NameAssignment_1");
					put(grammarAccess.getPlaceAccess().getTokensAssignment_3_0_2(), "rule__Place__TokensAssignment_3_0_2");
					put(grammarAccess.getPlaceAccess().getOutAssignment_3_1_2(), "rule__Place__OutAssignment_3_1_2");
					put(grammarAccess.getPlaceAccess().getInAssignment_3_2_2(), "rule__Place__InAssignment_3_2_2");
					put(grammarAccess.getTransitionAccess().getNameAssignment_1(), "rule__Transition__NameAssignment_1");
					put(grammarAccess.getTransitionAccess().getOutAssignment_3_0_2(), "rule__Transition__OutAssignment_3_0_2");
					put(grammarAccess.getTransitionAccess().getInAssignment_3_1_2(), "rule__Transition__InAssignment_3_1_2");
					put(grammarAccess.getPTArcAccess().getNameAssignment_1(), "rule__PTArc__NameAssignment_1");
					put(grammarAccess.getPTArcAccess().getWeightAssignment_3(), "rule__PTArc__WeightAssignment_3");
					put(grammarAccess.getPTArcAccess().getSourceAssignment_5(), "rule__PTArc__SourceAssignment_5");
					put(grammarAccess.getPTArcAccess().getTargetAssignment_7(), "rule__PTArc__TargetAssignment_7");
					put(grammarAccess.getTPArcAccess().getNameAssignment_1(), "rule__TPArc__NameAssignment_1");
					put(grammarAccess.getTPArcAccess().getWeightAssignment_3(), "rule__TPArc__WeightAssignment_3");
					put(grammarAccess.getTPArcAccess().getSourceAssignment_5(), "rule__TPArc__SourceAssignment_5");
					put(grammarAccess.getTPArcAccess().getTargetAssignment_7(), "rule__TPArc__TargetAssignment_7");
				}
			};
		}
		return nameMappings.get(element);
	}
			
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public PetrinetGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(PetrinetGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
