/**
 * generated by Xtext 2.12.0
 */
package mdd.uni.petrinet.petrinet;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Petrinet</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link mdd.uni.petrinet.petrinet.Petrinet#getName <em>Name</em>}</li>
 *   <li>{@link mdd.uni.petrinet.petrinet.Petrinet#getPlaces <em>Places</em>}</li>
 *   <li>{@link mdd.uni.petrinet.petrinet.Petrinet#getTransitions <em>Transitions</em>}</li>
 *   <li>{@link mdd.uni.petrinet.petrinet.Petrinet#getArcs <em>Arcs</em>}</li>
 * </ul>
 *
 * @see mdd.uni.petrinet.petrinet.PetrinetPackage#getPetrinet()
 * @model
 * @generated
 */
public interface Petrinet extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see mdd.uni.petrinet.petrinet.PetrinetPackage#getPetrinet_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link mdd.uni.petrinet.petrinet.Petrinet#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Places</b></em>' containment reference list.
   * The list contents are of type {@link mdd.uni.petrinet.petrinet.Place}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Places</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Places</em>' containment reference list.
   * @see mdd.uni.petrinet.petrinet.PetrinetPackage#getPetrinet_Places()
   * @model containment="true"
   * @generated
   */
  EList<Place> getPlaces();

  /**
   * Returns the value of the '<em><b>Transitions</b></em>' containment reference list.
   * The list contents are of type {@link mdd.uni.petrinet.petrinet.Transition}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Transitions</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Transitions</em>' containment reference list.
   * @see mdd.uni.petrinet.petrinet.PetrinetPackage#getPetrinet_Transitions()
   * @model containment="true"
   * @generated
   */
  EList<Transition> getTransitions();

  /**
   * Returns the value of the '<em><b>Arcs</b></em>' containment reference list.
   * The list contents are of type {@link mdd.uni.petrinet.petrinet.Arc}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Arcs</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Arcs</em>' containment reference list.
   * @see mdd.uni.petrinet.petrinet.PetrinetPackage#getPetrinet_Arcs()
   * @model containment="true"
   * @generated
   */
  EList<Arc> getArcs();

} // Petrinet
