/**
 * generated by Xtext 2.12.0
 */
package mdd.uni.petrinet.petrinet;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Token</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see mdd.uni.petrinet.petrinet.PetrinetPackage#getToken()
 * @model
 * @generated
 */
public interface Token extends EObject
{
} // Token
