/*
 * generated by Xtext 2.12.0
 */
package mdd.uni.petrinet.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class PetrinetAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("mdd/uni/petrinet/parser/antlr/internal/InternalPetrinet.tokens");
	}
}
