/*
 * generated by Xtext 2.12.0
 */
package mdd.uni.petrinet.parser.antlr;

import com.google.inject.Inject;
import mdd.uni.petrinet.parser.antlr.internal.InternalPetrinetParser;
import mdd.uni.petrinet.services.PetrinetGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class PetrinetParser extends AbstractAntlrParser {

	@Inject
	private PetrinetGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalPetrinetParser createParser(XtextTokenStream stream) {
		return new InternalPetrinetParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Petrinet";
	}

	public PetrinetGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(PetrinetGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
