/*
 * generated by Xtext 2.12.0
 */
package mdd.uni.petrinet.tests

import com.google.inject.Inject
import mdd.uni.petrinet.petrinet.Petrinet
import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.XtextRunner
import org.eclipse.xtext.testing.util.ParseHelper
import org.junit.Assert
import org.junit.Test
import org.junit.runner.RunWith

@RunWith(XtextRunner)
@InjectWith(PetrinetInjectorProvider)
class PetrinetParsingTest {
	@Inject
	ParseHelper<Petrinet> parseHelper
	
	@Test
	def void loadModel() {
		val result = parseHelper.parse('''
			Hello Xtext!
		''')
		Assert.assertNotNull(result)
		Assert.assertTrue(result.eResource.errors.isEmpty)
	}
}
