/**
 * generated by Xtext 2.12.0
 */
package org.xtext.example.mydsl.petriNetz;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Arc</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.petriNetz.Arc#getWeight <em>Weight</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.petriNetz.PetriNetzPackage#getArc()
 * @model
 * @generated
 */
public interface Arc extends EObject
{
  /**
   * Returns the value of the '<em><b>Weight</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Weight</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Weight</em>' attribute.
   * @see #setWeight(int)
   * @see org.xtext.example.mydsl.petriNetz.PetriNetzPackage#getArc_Weight()
   * @model
   * @generated
   */
  int getWeight();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.petriNetz.Arc#getWeight <em>Weight</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Weight</em>' attribute.
   * @see #getWeight()
   * @generated
   */
  void setWeight(int value);

} // Arc
