/**
 * generated by Xtext 2.12.0
 */
package org.xtext.example.mydsl.petriNetz;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.example.mydsl.petriNetz.PetriNetzFactory
 * @model kind="package"
 * @generated
 */
public interface PetriNetzPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "petriNetz";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.org/example/mydsl/PetriNetz";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "petriNetz";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  PetriNetzPackage eINSTANCE = org.xtext.example.mydsl.petriNetz.impl.PetriNetzPackageImpl.init();

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.petriNetz.impl.PetrinetImpl <em>Petrinet</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.petriNetz.impl.PetrinetImpl
   * @see org.xtext.example.mydsl.petriNetz.impl.PetriNetzPackageImpl#getPetrinet()
   * @generated
   */
  int PETRINET = 0;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PETRINET__NAME = 0;

  /**
   * The feature id for the '<em><b>Places</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PETRINET__PLACES = 1;

  /**
   * The feature id for the '<em><b>Transitions</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PETRINET__TRANSITIONS = 2;

  /**
   * The feature id for the '<em><b>Arcs</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PETRINET__ARCS = 3;

  /**
   * The number of structural features of the '<em>Petrinet</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PETRINET_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.petriNetz.impl.PlaceImpl <em>Place</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.petriNetz.impl.PlaceImpl
   * @see org.xtext.example.mydsl.petriNetz.impl.PetriNetzPackageImpl#getPlace()
   * @generated
   */
  int PLACE = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PLACE__NAME = 0;

  /**
   * The feature id for the '<em><b>Tokens</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PLACE__TOKENS = 1;

  /**
   * The feature id for the '<em><b>Out</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PLACE__OUT = 2;

  /**
   * The feature id for the '<em><b>In</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PLACE__IN = 3;

  /**
   * The number of structural features of the '<em>Place</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PLACE_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.petriNetz.impl.TokenImpl <em>Token</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.petriNetz.impl.TokenImpl
   * @see org.xtext.example.mydsl.petriNetz.impl.PetriNetzPackageImpl#getToken()
   * @generated
   */
  int TOKEN = 2;

  /**
   * The number of structural features of the '<em>Token</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TOKEN_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.petriNetz.impl.TransitionImpl <em>Transition</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.petriNetz.impl.TransitionImpl
   * @see org.xtext.example.mydsl.petriNetz.impl.PetriNetzPackageImpl#getTransition()
   * @generated
   */
  int TRANSITION = 3;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRANSITION__NAME = 0;

  /**
   * The feature id for the '<em><b>In</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRANSITION__IN = 1;

  /**
   * The feature id for the '<em><b>Out</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRANSITION__OUT = 2;

  /**
   * The number of structural features of the '<em>Transition</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRANSITION_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.petriNetz.impl.ArcImpl <em>Arc</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.petriNetz.impl.ArcImpl
   * @see org.xtext.example.mydsl.petriNetz.impl.PetriNetzPackageImpl#getArc()
   * @generated
   */
  int ARC = 4;

  /**
   * The feature id for the '<em><b>Weight</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ARC__WEIGHT = 0;

  /**
   * The number of structural features of the '<em>Arc</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ARC_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.petriNetz.impl.PTArcImpl <em>PT Arc</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.petriNetz.impl.PTArcImpl
   * @see org.xtext.example.mydsl.petriNetz.impl.PetriNetzPackageImpl#getPTArc()
   * @generated
   */
  int PT_ARC = 5;

  /**
   * The feature id for the '<em><b>Weight</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PT_ARC__WEIGHT = ARC__WEIGHT;

  /**
   * The feature id for the '<em><b>Src</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PT_ARC__SRC = ARC_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Trg</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PT_ARC__TRG = ARC_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>PT Arc</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PT_ARC_FEATURE_COUNT = ARC_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.petriNetz.impl.TPArcImpl <em>TP Arc</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.petriNetz.impl.TPArcImpl
   * @see org.xtext.example.mydsl.petriNetz.impl.PetriNetzPackageImpl#getTPArc()
   * @generated
   */
  int TP_ARC = 6;

  /**
   * The feature id for the '<em><b>Weight</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TP_ARC__WEIGHT = ARC__WEIGHT;

  /**
   * The feature id for the '<em><b>Trg</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TP_ARC__TRG = ARC_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Src</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TP_ARC__SRC = ARC_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>TP Arc</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TP_ARC_FEATURE_COUNT = ARC_FEATURE_COUNT + 2;


  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.petriNetz.Petrinet <em>Petrinet</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Petrinet</em>'.
   * @see org.xtext.example.mydsl.petriNetz.Petrinet
   * @generated
   */
  EClass getPetrinet();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.petriNetz.Petrinet#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.mydsl.petriNetz.Petrinet#getName()
   * @see #getPetrinet()
   * @generated
   */
  EAttribute getPetrinet_Name();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.petriNetz.Petrinet#getPlaces <em>Places</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Places</em>'.
   * @see org.xtext.example.mydsl.petriNetz.Petrinet#getPlaces()
   * @see #getPetrinet()
   * @generated
   */
  EReference getPetrinet_Places();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.petriNetz.Petrinet#getTransitions <em>Transitions</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Transitions</em>'.
   * @see org.xtext.example.mydsl.petriNetz.Petrinet#getTransitions()
   * @see #getPetrinet()
   * @generated
   */
  EReference getPetrinet_Transitions();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.petriNetz.Petrinet#getArcs <em>Arcs</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Arcs</em>'.
   * @see org.xtext.example.mydsl.petriNetz.Petrinet#getArcs()
   * @see #getPetrinet()
   * @generated
   */
  EReference getPetrinet_Arcs();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.petriNetz.Place <em>Place</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Place</em>'.
   * @see org.xtext.example.mydsl.petriNetz.Place
   * @generated
   */
  EClass getPlace();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.petriNetz.Place#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.mydsl.petriNetz.Place#getName()
   * @see #getPlace()
   * @generated
   */
  EAttribute getPlace_Name();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.petriNetz.Place#getTokens <em>Tokens</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Tokens</em>'.
   * @see org.xtext.example.mydsl.petriNetz.Place#getTokens()
   * @see #getPlace()
   * @generated
   */
  EReference getPlace_Tokens();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.petriNetz.Place#getOut <em>Out</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Out</em>'.
   * @see org.xtext.example.mydsl.petriNetz.Place#getOut()
   * @see #getPlace()
   * @generated
   */
  EReference getPlace_Out();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.petriNetz.Place#getIn <em>In</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>In</em>'.
   * @see org.xtext.example.mydsl.petriNetz.Place#getIn()
   * @see #getPlace()
   * @generated
   */
  EReference getPlace_In();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.petriNetz.Token <em>Token</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Token</em>'.
   * @see org.xtext.example.mydsl.petriNetz.Token
   * @generated
   */
  EClass getToken();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.petriNetz.Transition <em>Transition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Transition</em>'.
   * @see org.xtext.example.mydsl.petriNetz.Transition
   * @generated
   */
  EClass getTransition();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.petriNetz.Transition#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.mydsl.petriNetz.Transition#getName()
   * @see #getTransition()
   * @generated
   */
  EAttribute getTransition_Name();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.petriNetz.Transition#getIn <em>In</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>In</em>'.
   * @see org.xtext.example.mydsl.petriNetz.Transition#getIn()
   * @see #getTransition()
   * @generated
   */
  EReference getTransition_In();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.petriNetz.Transition#getOut <em>Out</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Out</em>'.
   * @see org.xtext.example.mydsl.petriNetz.Transition#getOut()
   * @see #getTransition()
   * @generated
   */
  EReference getTransition_Out();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.petriNetz.Arc <em>Arc</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Arc</em>'.
   * @see org.xtext.example.mydsl.petriNetz.Arc
   * @generated
   */
  EClass getArc();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.petriNetz.Arc#getWeight <em>Weight</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Weight</em>'.
   * @see org.xtext.example.mydsl.petriNetz.Arc#getWeight()
   * @see #getArc()
   * @generated
   */
  EAttribute getArc_Weight();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.petriNetz.PTArc <em>PT Arc</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>PT Arc</em>'.
   * @see org.xtext.example.mydsl.petriNetz.PTArc
   * @generated
   */
  EClass getPTArc();

  /**
   * Returns the meta object for the reference '{@link org.xtext.example.mydsl.petriNetz.PTArc#getSrc <em>Src</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Src</em>'.
   * @see org.xtext.example.mydsl.petriNetz.PTArc#getSrc()
   * @see #getPTArc()
   * @generated
   */
  EReference getPTArc_Src();

  /**
   * Returns the meta object for the reference '{@link org.xtext.example.mydsl.petriNetz.PTArc#getTrg <em>Trg</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Trg</em>'.
   * @see org.xtext.example.mydsl.petriNetz.PTArc#getTrg()
   * @see #getPTArc()
   * @generated
   */
  EReference getPTArc_Trg();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.petriNetz.TPArc <em>TP Arc</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>TP Arc</em>'.
   * @see org.xtext.example.mydsl.petriNetz.TPArc
   * @generated
   */
  EClass getTPArc();

  /**
   * Returns the meta object for the reference '{@link org.xtext.example.mydsl.petriNetz.TPArc#getTrg <em>Trg</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Trg</em>'.
   * @see org.xtext.example.mydsl.petriNetz.TPArc#getTrg()
   * @see #getTPArc()
   * @generated
   */
  EReference getTPArc_Trg();

  /**
   * Returns the meta object for the reference '{@link org.xtext.example.mydsl.petriNetz.TPArc#getSrc <em>Src</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Src</em>'.
   * @see org.xtext.example.mydsl.petriNetz.TPArc#getSrc()
   * @see #getTPArc()
   * @generated
   */
  EReference getTPArc_Src();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  PetriNetzFactory getPetriNetzFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.petriNetz.impl.PetrinetImpl <em>Petrinet</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.petriNetz.impl.PetrinetImpl
     * @see org.xtext.example.mydsl.petriNetz.impl.PetriNetzPackageImpl#getPetrinet()
     * @generated
     */
    EClass PETRINET = eINSTANCE.getPetrinet();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PETRINET__NAME = eINSTANCE.getPetrinet_Name();

    /**
     * The meta object literal for the '<em><b>Places</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PETRINET__PLACES = eINSTANCE.getPetrinet_Places();

    /**
     * The meta object literal for the '<em><b>Transitions</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PETRINET__TRANSITIONS = eINSTANCE.getPetrinet_Transitions();

    /**
     * The meta object literal for the '<em><b>Arcs</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PETRINET__ARCS = eINSTANCE.getPetrinet_Arcs();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.petriNetz.impl.PlaceImpl <em>Place</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.petriNetz.impl.PlaceImpl
     * @see org.xtext.example.mydsl.petriNetz.impl.PetriNetzPackageImpl#getPlace()
     * @generated
     */
    EClass PLACE = eINSTANCE.getPlace();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PLACE__NAME = eINSTANCE.getPlace_Name();

    /**
     * The meta object literal for the '<em><b>Tokens</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PLACE__TOKENS = eINSTANCE.getPlace_Tokens();

    /**
     * The meta object literal for the '<em><b>Out</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PLACE__OUT = eINSTANCE.getPlace_Out();

    /**
     * The meta object literal for the '<em><b>In</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PLACE__IN = eINSTANCE.getPlace_In();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.petriNetz.impl.TokenImpl <em>Token</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.petriNetz.impl.TokenImpl
     * @see org.xtext.example.mydsl.petriNetz.impl.PetriNetzPackageImpl#getToken()
     * @generated
     */
    EClass TOKEN = eINSTANCE.getToken();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.petriNetz.impl.TransitionImpl <em>Transition</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.petriNetz.impl.TransitionImpl
     * @see org.xtext.example.mydsl.petriNetz.impl.PetriNetzPackageImpl#getTransition()
     * @generated
     */
    EClass TRANSITION = eINSTANCE.getTransition();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TRANSITION__NAME = eINSTANCE.getTransition_Name();

    /**
     * The meta object literal for the '<em><b>In</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TRANSITION__IN = eINSTANCE.getTransition_In();

    /**
     * The meta object literal for the '<em><b>Out</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TRANSITION__OUT = eINSTANCE.getTransition_Out();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.petriNetz.impl.ArcImpl <em>Arc</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.petriNetz.impl.ArcImpl
     * @see org.xtext.example.mydsl.petriNetz.impl.PetriNetzPackageImpl#getArc()
     * @generated
     */
    EClass ARC = eINSTANCE.getArc();

    /**
     * The meta object literal for the '<em><b>Weight</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ARC__WEIGHT = eINSTANCE.getArc_Weight();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.petriNetz.impl.PTArcImpl <em>PT Arc</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.petriNetz.impl.PTArcImpl
     * @see org.xtext.example.mydsl.petriNetz.impl.PetriNetzPackageImpl#getPTArc()
     * @generated
     */
    EClass PT_ARC = eINSTANCE.getPTArc();

    /**
     * The meta object literal for the '<em><b>Src</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PT_ARC__SRC = eINSTANCE.getPTArc_Src();

    /**
     * The meta object literal for the '<em><b>Trg</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PT_ARC__TRG = eINSTANCE.getPTArc_Trg();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.petriNetz.impl.TPArcImpl <em>TP Arc</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.petriNetz.impl.TPArcImpl
     * @see org.xtext.example.mydsl.petriNetz.impl.PetriNetzPackageImpl#getTPArc()
     * @generated
     */
    EClass TP_ARC = eINSTANCE.getTPArc();

    /**
     * The meta object literal for the '<em><b>Trg</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TP_ARC__TRG = eINSTANCE.getTPArc_Trg();

    /**
     * The meta object literal for the '<em><b>Src</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TP_ARC__SRC = eINSTANCE.getTPArc_Src();

  }

} //PetriNetzPackage
