/**
 * generated by Xtext 2.12.0
 */
package org.xtext.example.mydsl.petriNetz;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>PT Arc</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.petriNetz.PTArc#getSrc <em>Src</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.petriNetz.PTArc#getTrg <em>Trg</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.petriNetz.PetriNetzPackage#getPTArc()
 * @model
 * @generated
 */
public interface PTArc extends Arc
{
  /**
   * Returns the value of the '<em><b>Src</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Src</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Src</em>' reference.
   * @see #setSrc(Place)
   * @see org.xtext.example.mydsl.petriNetz.PetriNetzPackage#getPTArc_Src()
   * @model
   * @generated
   */
  Place getSrc();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.petriNetz.PTArc#getSrc <em>Src</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Src</em>' reference.
   * @see #getSrc()
   * @generated
   */
  void setSrc(Place value);

  /**
   * Returns the value of the '<em><b>Trg</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Trg</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Trg</em>' reference.
   * @see #setTrg(Transition)
   * @see org.xtext.example.mydsl.petriNetz.PetriNetzPackage#getPTArc_Trg()
   * @model
   * @generated
   */
  Transition getTrg();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.petriNetz.PTArc#getTrg <em>Trg</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Trg</em>' reference.
   * @see #getTrg()
   * @generated
   */
  void setTrg(Transition value);

} // PTArc
