/**
 * generated by Xtext 2.12.0
 */
package org.xtext.example.mydsl.petriNetz;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Token</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.example.mydsl.petriNetz.PetriNetzPackage#getToken()
 * @model
 * @generated
 */
public interface Token extends EObject
{
} // Token
