/*
 * generated by Xtext 2.12.0
 */
package mdd.uni.petrinet.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractPetrinetScopeProvider extends DelegatingScopeProvider {
}
