/*
 * generated by Xtext 2.12.0
 */
package mdd.uni.petrinet.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractPetrinetValidator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>();
		result.add(mdd.uni.petrinet.petrinet.PetrinetPackage.eINSTANCE);
		return result;
	}
	
}
