/*
 * generated by Xtext 2.12.0
 */
package mdd.uni.petrinet


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class PetrinetRuntimeModule extends AbstractPetrinetRuntimeModule {
}
