/**
 * generated by Xtext 2.12.0
 */
package org.xtext.example.mydsl.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.xtext.example.mydsl.PetriNetzRuntimeModule;
import org.xtext.example.mydsl.PetriNetzStandaloneSetup;
import org.xtext.example.mydsl.ide.PetriNetzIdeModule;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class PetriNetzIdeSetup extends PetriNetzStandaloneSetup {
  @Override
  public Injector createInjector() {
    PetriNetzRuntimeModule _petriNetzRuntimeModule = new PetriNetzRuntimeModule();
    PetriNetzIdeModule _petriNetzIdeModule = new PetriNetzIdeModule();
    return Guice.createInjector(Modules2.mixin(_petriNetzRuntimeModule, _petriNetzIdeModule));
  }
}
