/*
 * generated by Xtext 2.12.0
 */
package org.xtext.example.mydsl.ide.contentassist.antlr;

import com.google.inject.Inject;
import java.util.HashMap;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;
import org.xtext.example.mydsl.ide.contentassist.antlr.internal.InternalPetriNetzParser;
import org.xtext.example.mydsl.services.PetriNetzGrammarAccess;

public class PetriNetzParser extends AbstractContentAssistParser {

	@Inject
	private PetriNetzGrammarAccess grammarAccess;

	private Map<AbstractElement, String> nameMappings;

	@Override
	protected InternalPetriNetzParser createParser() {
		InternalPetriNetzParser result = new InternalPetriNetzParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getArcAccess().getAlternatives_0(), "rule__Arc__Alternatives_0");
					put(grammarAccess.getPetrinetAccess().getGroup(), "rule__Petrinet__Group__0");
					put(grammarAccess.getPlaceAccess().getGroup(), "rule__Place__Group__0");
					put(grammarAccess.getPlaceAccess().getGroup_3(), "rule__Place__Group_3__0");
					put(grammarAccess.getPlaceAccess().getGroup_3_1(), "rule__Place__Group_3_1__0");
					put(grammarAccess.getPlaceAccess().getGroup_5(), "rule__Place__Group_5__0");
					put(grammarAccess.getPlaceAccess().getGroup_5_3(), "rule__Place__Group_5_3__0");
					put(grammarAccess.getPlaceAccess().getGroup_6(), "rule__Place__Group_6__0");
					put(grammarAccess.getPlaceAccess().getGroup_6_3(), "rule__Place__Group_6_3__0");
					put(grammarAccess.getTokenAccess().getGroup(), "rule__Token__Group__0");
					put(grammarAccess.getTransitionAccess().getGroup(), "rule__Transition__Group__0");
					put(grammarAccess.getTransitionAccess().getGroup_4(), "rule__Transition__Group_4__0");
					put(grammarAccess.getTransitionAccess().getGroup_4_3(), "rule__Transition__Group_4_3__0");
					put(grammarAccess.getTransitionAccess().getGroup_5(), "rule__Transition__Group_5__0");
					put(grammarAccess.getTransitionAccess().getGroup_5_3(), "rule__Transition__Group_5_3__0");
					put(grammarAccess.getArcAccess().getGroup(), "rule__Arc__Group__0");
					put(grammarAccess.getPTArcAccess().getGroup(), "rule__PTArc__Group__0");
					put(grammarAccess.getTPArcAccess().getGroup(), "rule__TPArc__Group__0");
					put(grammarAccess.getPetrinetAccess().getNameAssignment_1(), "rule__Petrinet__NameAssignment_1");
					put(grammarAccess.getPetrinetAccess().getPlacesAssignment_3(), "rule__Petrinet__PlacesAssignment_3");
					put(grammarAccess.getPetrinetAccess().getTransitionsAssignment_4(), "rule__Petrinet__TransitionsAssignment_4");
					put(grammarAccess.getPetrinetAccess().getArcsAssignment_5(), "rule__Petrinet__ArcsAssignment_5");
					put(grammarAccess.getPlaceAccess().getNameAssignment_1(), "rule__Place__NameAssignment_1");
					put(grammarAccess.getPlaceAccess().getTokensAssignment_3_0(), "rule__Place__TokensAssignment_3_0");
					put(grammarAccess.getPlaceAccess().getTokensAssignment_3_1_1(), "rule__Place__TokensAssignment_3_1_1");
					put(grammarAccess.getPlaceAccess().getOutAssignment_5_2(), "rule__Place__OutAssignment_5_2");
					put(grammarAccess.getPlaceAccess().getOutAssignment_5_3_1(), "rule__Place__OutAssignment_5_3_1");
					put(grammarAccess.getPlaceAccess().getInAssignment_6_2(), "rule__Place__InAssignment_6_2");
					put(grammarAccess.getPlaceAccess().getInAssignment_6_3_1(), "rule__Place__InAssignment_6_3_1");
					put(grammarAccess.getTransitionAccess().getNameAssignment_1(), "rule__Transition__NameAssignment_1");
					put(grammarAccess.getTransitionAccess().getInAssignment_4_2(), "rule__Transition__InAssignment_4_2");
					put(grammarAccess.getTransitionAccess().getInAssignment_4_3_1(), "rule__Transition__InAssignment_4_3_1");
					put(grammarAccess.getTransitionAccess().getOutAssignment_5_2(), "rule__Transition__OutAssignment_5_2");
					put(grammarAccess.getTransitionAccess().getOutAssignment_5_3_1(), "rule__Transition__OutAssignment_5_3_1");
					put(grammarAccess.getArcAccess().getWeightAssignment_2(), "rule__Arc__WeightAssignment_2");
					put(grammarAccess.getPTArcAccess().getSrcAssignment_1(), "rule__PTArc__SrcAssignment_1");
					put(grammarAccess.getPTArcAccess().getTrgAssignment_3(), "rule__PTArc__TrgAssignment_3");
					put(grammarAccess.getTPArcAccess().getTrgAssignment_1(), "rule__TPArc__TrgAssignment_1");
					put(grammarAccess.getTPArcAccess().getSrcAssignment_3(), "rule__TPArc__SrcAssignment_3");
				}
			};
		}
		return nameMappings.get(element);
	}
			
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public PetriNetzGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(PetriNetzGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
