/**
 * generated by Xtext 2.12.0
 */
package org.xtext.example.mydsl;

import org.xtext.example.mydsl.PetriNetzStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class PetriNetzStandaloneSetup extends PetriNetzStandaloneSetupGenerated {
  public static void doSetup() {
    new PetriNetzStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
