/*
 * generated by Xtext 2.12.0
 */
package mdd.uni.petrinet.ide

import com.google.inject.Guice
import mdd.uni.petrinet.PetrinetRuntimeModule
import mdd.uni.petrinet.PetrinetStandaloneSetup
import org.eclipse.xtext.util.Modules2

/**
 * Initialization support for running Xtext languages as language servers.
 */
class PetrinetIdeSetup extends PetrinetStandaloneSetup {

	override createInjector() {
		Guice.createInjector(Modules2.mixin(new PetrinetRuntimeModule, new PetrinetIdeModule))
	}
	
}
